language: ruby
rvm:
- 2.7.1
sudo: false
script: bundle exec rake deploy
env:
  global:
  - secure: j9ZujbS+0vf4oWHyZX04DyaY6RjT+52An9rt0s4Rypzcov5Aw6pJEIxzIe0SGrOsKVpYzC0OO9f7c1OeNPTfOZCFYc1gqV2YGUCQIxnYAhSIK5SHE1edEnxhepnR83PMUvzKGHbup0szFGCrwyXO9evfexboVMYNcHZVXUrMrB4HVfV7RExTPVStEl7zDRg/MU9YNDFFDHr8w0lzqV58Dy1Le2HWUFQ6njmFjNk1dgg8wgSRkbNzmShjDxbbllceXeFRffRs8YMCE05UMYa+UVDuPzghGIc3+WwruVPUTiQ4emZ4Hjm+G+pafgY3vqO173aVvZyUIUMieRH+c0hvhTXQDLNxwQXTgIOMdc+5fvxjCDrQYSMhs5v8ZuOQibxqcAhFJpI1bOpXbYSHEvWzV96oA5eqTfVRiBCYYjIeet2KN5JWD1Kmrk0avyaiY8xIc5JJki+rRx+B59ro/7lvVEFSriUx59nkqWB2Lzl6Y/0brSwxr2BVHcb8phyPj6X+IGebA8mQ/seoSmeOemeiPeUBWeq41kQozbs0LzDakDos5fUpcylhjvXMd/JKlC3T0KYBad/oRayttG1cTjFwRNCAj0HEYsyzoZshVukFDbcNpVLNzB+leoZM/zhpXO1HqwwElD/I6GiDJMBfcvP3om8hQBHUlxM/Jc+10RdTcZE=
