language: ruby
rvm:
- 2.7.1
sudo: false
script: bundle exec rake deploy
env:
  global:
  - secure: SQT7CcFOxYXIQ+I3m4pfx8Dyjl7dYugMRi+o4c5jUD4knkLn2IGlPdD6MJ3Ua67Yl68+xYyT4Mj4aeqI93g9CZWAViUJQInv/q2g/HFkG12HzdwBwkkZ7VJlWWjScZ9Z6XX1WaYQpXyj8W/6JG+Hr2N7NympSZcY+L04Xv5vAmPFJBqwyZCna3rTR90OHM+1KSBJMSLxKAmu6BHRWADtlQIS9gqMAv6iqtrEvuqhmtBDJALuk+dfemmjJYDUal9XID3gFLuxWQmUOHJzY6LKTj2LK41mrXjvcsN35jsgW4+YI/8kyqhi4HHrt94Fgfeb2hDGSjCSpTfkEoZ/Wm/SgTStJHeuWSsSeCd4k6rPwwKGRGqRJld412TNJaisEmSrDtCOHo5e+ZyCVTpkKLYjIwQP9mfiAEXSkoz2CakvIQzNu3oH7o7/tk3obsBzt1P8oKWlNBobRhlsU2YjrRROgHhluKmWvxvobEUbjOxWCKOJHCbXc0auaRUI3/AUa71pHydA9n6DtcPJ8XqUqJZtJ8qhC/BZh/HHM5ivzp8JvDTYj4hEWYMg4dsA1F7gbQcX3ku8LCFEoiTmj/aOwAeV4dNTsKkCTv4/eWQv20K+ZtzbcpuYireYrQlpUIXugu/Mpxprs6Q9NbeygSbkjekigP2E9rFl5C0pngLpi9LQNb0=
