language: ruby
rvm:
- 2.7.1
sudo: false
script: bundle exec rake deploy
env:
  global:
  - secure: LPlGc6j+eEwsedN4ZeTM2RUndJxMwUPj4ZIn7fv1amEp5Czfv6Iwcryj702/J0J7OlRZD2DULdEIH+uhFnP+MDArATabkPWbeSCLjeF75kww84QRN8eoD///7427rozggiN2lGZRv+LwkZ+mG4z3v+Vhsup56c6/wj+L1touzOJRxMybNuKuWGzvnQU3uY8UuZKfffJJtbh6Z+QzvxcLOEbTWeuS7uTXec9pXQbmTyf8MYVioEpHtltbwWIxCt/4X6jcuoWgTM8r9+dV7oIpjkfclkS9KFw+N+JYfNtlnT0jKAcN/Fh3ECWIsBB2DngL77dKyNFy9sobxCy5hytriTaq+KdrWHZCZZwgQC28HGp+ll4s2yeNTfUQGnrkgx6K2E4jSgdEAV2/vACEViewH94CUHxMMxIlmd/XJnOtFusXYYNKlFnAO0XC5dUz4+75Vf92MvTla+sEGRJbomWDeoZ7NnnD5ZzRbFoplW0OV/Cw6nrCRoa9lbUCGsJgEPY/DLjbsDT77ql4I9JaUPY5ASz9FgJ4KjlZnOlr15sUrs5edbPaMPXf/pM78FbhM0ShC6Kw92LuwTulDT5Ye7sco2OuEsCsblLU8shjX8KIyJ3BYiMWRfJ+QUorv3eC2fdVz0Uub8x44a2jdkMSOsZ8h+QRYPFKEMFY2EkNOJATZns=
