language: ruby
rvm:
- 2.7.1
sudo: false
script: bundle exec rake deploy
env:
  global:
  - secure: rVWbaQQF/N+RbD6pgD2r3/sOyLa866+2WB1F2Zf5ZCcbzxaZLexkeOMsvXMMandaBlRLmJ3H1ql9fwtOK47KlnuQJdARIcoA0VXK+UY2afn5qB2iG4iHmrQHLVUGQRQsmrcGAjJaMhmNVXodOVf4VoY9mKbXjqNFHD6tBKIB4gJUust6CvWsUtL/R6wobodz9Qg4uKSWqkjhFx6H54iVOwUW0HizGq1VDxR5ncNtcrQ0/n26HnMQ4NrMoHqOF6WWRMR6dJxivnqp2gVZF4vC9laGD5pgHlRpO6OwZYcmuX6jCCgJL0X8MIHdHKRVzHZIhmSOeoyk81i8D7J159nYuKFuRiTs8Bcu3IZv8noP6adKuY6K5RC8dTzVQSYwWXcfrQx43STVcEf2HxSjbJjxYy1yrkqelJZr/3UoITq4YZ5iJWnjj0zn+KsrLYYS3GTNfz1Lls7123d6eo3MQeqaYE46UfdrBNEpOzfQPDq2J8DkSdqZzaktlb0z51V80DK9AbZ5WXkCF5wRK6dpHMjtthZKO3nNu1QzhBlSC6X6yBTkd2xdG+SJBgGIbVDXyHrLpY0ljNu3lW0piTDJXeXnzaM1E1FxFsMNGksChdSBSKcH705Xi92lLjo9P35STPod6IWroIKNX+3F1UQrvXljh0K1DzRQgRcMHtamLk5RZTE=
