# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A journey into functionnal programming wonders, especially Clojure and Clojurescript
email: raphael.boukara@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   A journey into functionnal programming wonders, especially Clojure and Clojurescript
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.klipse.tech/" # the base hostname & protocol for your site
github_username:  raphaelboukara
author: Raphael Boukara

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
